[package]
name = "polycash_zk_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.3", default-features = false, features = ['std'] }
contracts = { path = "../../../contracts" }
smartstring = "1.0.1"
